services:
  - type: web
    name: pos-lite
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: "" # Already handled in Dockerfile
    startCommand: "" # Already handled in Dockerfile