services:
  - type: web
    name: pos-lite
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: "" # Already handled in Dockerfile
    startCommand: "" # Already handled in Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://santi-pos-lite.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
    deployHook: bash deploy.sh